#!/bin/sh
mvn clean package
docker build -t PatelShakil/LiveMSAResource .
docker rm -f LiveMSAResource 2>/dev/null || true
docker run -it --name LiveMSAResource -p 8080:8080 --name LiveMSAResource PatelShakil/LiveMSAResource
